name: ZipPluginLoader
main: ZipPluginLoader\Main
version: 1.1.3
api: 2.0.0
load: STARTUP
author: aliuly
description: Load Zip packed plugins
website: https://github.com/alejandroliu/pocketmine-plugins/tree/master/ZipPluginLoader
